### ISSUE TITLE
MAVIC 2 ENTERPRISE thermal data are not correct

### ISSUE THREAD

**Issue by PaoloF1990** [detecttechnologies/thermal_base#16]
Hi, I tried your algorithm and I found that the output thermal data are very different from the ones we expected (we used DJI Thermal Analysis Tool as comparison).
We tried to change the metadata internally and setting the correct values of emissivity, object distance, atmospheric temperature, reflected apparent temperature, IR window temperature, IR window transmission and relative humidity, but this didn't improve the results. Specifically, in hour image there is a marker that should be at -30°C and it is obtained at 20°C. Is this an effect of Plank constants? Is there any way to obtain them?

**Comment by hongsamvo** [comment]
I got the same issue too

**Comment by rsnk96** [comment]
Hey folks

This project isn't being actively maintained anymore, apologies!
