### ISSUE TITLE
Readme and Project structure updates

### ISSUE THREAD

**Issue by rsnk96** [detecttechnologies/thermal_base#2]
1. Credit section: do mention raw2temp in ThermImage-R (https://github.com/gtatters/Thermimage), exiftool, flyr
2. When user clicks on the badge, can it redirect to the output on the Github workflows page ?(i.e. a commit-independent version of https://github.com/detecttechnologies/thermal_base/runs/3123657725?check_suite_focus=true)
3. In the `Usage` section, it's `from thermal_base.thermal_base import ThermalImage`. Is there any way we can make it `from thermal_base import ThermalImage`? Perhaps defining something in the `__init__.py` file?
4. In the `Usage` section, there's also a `from thermal_base import utils`. Can a user use the library without importing that library?
5. The `Disclaimer` section of the readme can be changed to `Supported formats`. Additionally, its content can be changed to something along the lines of

|  Data Format  |  Sample Cameras  |  Support  |
| --- | --- | --- |
|  FLIR RJPG with TIFF-format of thermal embedding |  Zenmuse XT-2 | ✅ |
|  FLIR RJPG with TIFF-format of thermal embedding |  FLIR E-4, T660 | ✅ |
|  DJI-encoded thermal image | Zenmuse H20-T | ✅ |
|  FLIR SEQ Thermal Video |  Zenmuse XT-2 | ✅ |
|  FLIR CSQ Thermal Video |  Zenmuse XT-2 | ❌ |

*RJPG is also known as R-JPEG

**Comment by mukheshpugal** [comment]
4. The `ThermalImageHelpers` class which resides in `utils.py` can be used from outside the library

**Comment by mukheshpugal** [comment]
Further discussion can be continued in #3
